# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pszTimestamp', models.TextField(max_length=1024)),
                ('maxMoney', models.BigIntegerField()),
                ('nSubsidyHalving', models.IntegerField()),
                ('port', models.IntegerField()),
                ('nTime', models.IntegerField()),
                ('nBits', models.CharField(max_length=40)),
                ('dnsSeed', models.CharField(max_length=30)),
                ('cAmountSubsidy', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FullNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='fullNodes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BonaB.FullNode'),
        ),
    ]
